version: "3.8"
services:
  write-db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: pass123
  read-db:
    image: mongo
    ports:
      - 27018:27017
    environment:
      - MONGODB_DATABASE="vf-read-db"
