###
POST http://localhost:3000/alarms HTTP/1.1
content-type: application/json

{
  "name": "Test Alarm",
  "severity": "high",
  "triggeredAt": "2021-01-01T00:00:00.000Z",
  "items": [
    {
      "name": "Item 1",
      "type": "TYPE_1"
    },
    {
      "name": "Item 2",
      "type": "TYPE_2"
    }
  ]
}

###
GET http://localhost:3000/alarms HTTP/1.1